version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeTest1710
  gitServerName: testProject
  gitUrl: https://github.com/rlakshitha0912/EdgeTest1710
  gitUsername: rlakshitha0912
  gitBranch: main
